language: python

# There are no tests yet

script: make test || true

after_failure:
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

after_success:
  # Download thesis
  - Rscript -e 'download.file("https://www.rug.nl/research/portal/files/132028374/Complete_thesis.pdf", tempfile())'

